model:
  output_dir: /data/gated_diffusion/
  model_path: timbrooks/instruct-pix2pix
  mask:
    act_fn

data:
  path: osunlp/MagicBrush

logging:
  dir: logs
  wandb_project: gated-diffusion

train:
  num_epochs: 200
  max_train_steps: 256
  batch_size: 8
  mixed_precision: fp16
  gradient_accumulation_steps: 4
  gradient_checkpointing: True
  checkpointing_steps: 500

  learning_rate: 3e-5
  lr_warmup_steps: 0
  lr_scheduler: constant

  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1e-2
  adam_epsilon: 1e-08

  max_grad_norm: 1.0

  seed: 0