model:
  output_dir: /data/gated_diffusion/
  model_path: timbrooks/instruct-pix2pix
  mask:
    act_fn: sigmoid

data:
  path: osunlp/MagicBrush
  val_path: val_dataset

logging:
  dir: logs
  wandb_project: gated-diffusion

train:
  num_epochs: 200
  validation_epochs: 1
  batch_size: 8
  mixed_precision: fp16
  gradient_accumulation_steps: 4
  gradient_checkpointing: True
  checkpointing_steps: 50

  unet_learning_rate: 1e-6
  mask_learning_rate: 1e-4 
  lr_warmup_steps: 0
  lr_scheduler: constant

  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1e-2
  adam_epsilon: 1e-08

  max_grad_norm: 1.0

  seed: 0
  resume_from_checkpoint:
  # resume_from_checkpoint: GD_run_4/checkpoints/checkpoint-500

  # joint_training: True - training eps unet + mask unet
  # joint_training: False - freeze eps unet
  joint_training: True
  hard_mask: True

inference:
  # last - apply mask to last timestep
  # all - apply mask on all timesteps
  # both
  # none - no mask
  method: last

